---
title: "Programmmerr's Blog"
date: 2021-12-26
---
title: Programmmerr's Blog
author: Programmmerr
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A learning path to github

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
